### ISSUE TITLE
Fix your unicode.

### ISSUE THREAD

**Issue by kberov** [caruana/GHUserGeoSearch#1]
I got an email saying:
Hi ÐšÑ€Ð°Ñ Ð¸Ð¼Ð¸Ñ€ Ð‘ÐµÑ€Ð¾Ð²,
....

This is not my name.
Then please stop spam.

**Comment by caruana** [comment]
Hi @kberov, I apologize for the character bug, the reason that happened is because I simply copied and pasted data into a MailChimp textbox which apparently didn't encode correctly. Thank you for alerting me to the problem and rest assured I will not email you again. 

This project was a small experiment that has had an overwhelmingly positive response from users. 

Going forward, I plan to write an api call directly into MailChimp which will fix the character encoding issue. All the best!
